version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todo_db
    depends_on:
      - db
    deploy:
      replicas: 2  
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13
    container_name: flask_todo_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4 
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "5050:80"  
    depends_on:
      - db  
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:  
  pgadmin-data:
